test: add Node.js 10 to Travis CI test matrix
stream-utils/destroy pull request #7
Opened 2018-10-22 17:06 UTC by watson

I'm not really sure why the other test-versions are pinned to a specific minor. Shouldn't they always just run against the latest minor, or is the pinned minor there to test against a specific bug in that version?

2018-10-22 17:10 UTC, dougwilson commented
They are pinned to minors because Node.js in experience breaks randomly. It is out policy to only pin against minors. Please pin this to the current minor.

2018-10-22 17:10 UTC, dougwilson requested changes
Pin to minor.

2018-10-22 18:03 UTC, watson commented
@dougwilson fixed

2018-10-23 00:04 UTC, dougwilson approved these changes

2018-10-23 00:05 UTC, merged